In [1]:
import torch

In [32]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

In [33]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### 1. 차원 크기 확인
* size()
* shape
* ndimension()

In [34]:
print(x.size())
print(x.shape)
print(x.ndimension())

torch.Size([3, 3])
torch.Size([3, 3])
2


### 2. 텐서의 원소 수를 유지하며 차원 변경
* unsqueeze() : 확대
* squeeze() : 축소
* view() : 사용자지정 변경

In [35]:
x = torch.unsqueeze(x, 0)
print(x)
print(x.size())
print(x.shape)
print(x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
3


In [36]:
x = torch.squeeze(x)
print(x)
print(x.size())
print(x.shape)
print(x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.Size([3, 3])
2


In [37]:
x = x.view(9)
print(x)
print(x.size())
print(x.shape)
print(x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
torch.Size([9])
1


In [38]:
try:
    x = x.view(2, 4)
except Exception as e:
    print(e)

shape '[2, 4]' is invalid for input of size 9


### 3. 행렬
* torch.mm() : 행렬곱

In [42]:
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

In [44]:
print("w size:", w.size())
print("x size:", x.size())
print(w)
print(x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
tensor([[ 0.3163,  0.9337,  1.0253],
        [ 0.9974, -0.5737, -0.4065],
        [ 1.6371, -1.1976, -0.2515],
        [ 0.5735,  0.3052, -0.8073],
        [ 1.1652, -0.9310,  0.0854]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [45]:
b = torch.randn(5, 2, dtype=torch.float)
print("b size: ", b.size())
print("b: ", b)

b size:  torch.Size([5, 2])
b:  tensor([[-0.7967, -0.9320],
        [-0.7925,  0.7896],
        [-1.3500,  0.0695],
        [-0.5672,  2.4628],
        [-0.1921, -0.6985]])


In [47]:
wx = torch.mm(w, x)
print("wx size: ", wx.size())
print("wx: ", wx)

wx size:  torch.Size([5, 2])
wx:  tensor([[ 8.2440, 10.5194],
        [-2.7559, -2.7387],
        [-3.2132, -3.0253],
        [-2.5474, -2.4760],
        [-1.2005, -0.8808]])


In [48]:
result = wx + b
print("result size: ", result.size())
print("result: ", result)

result size:  torch.Size([5, 2])
result:  tensor([[ 7.4474,  9.5874],
        [-3.5484, -1.9491],
        [-4.5632, -2.9558],
        [-3.1146, -0.0132],
        [-1.3926, -1.5794]])


### 4. Autograd
* 수식의 기울기를 자동으로 계산
* requires_grad=True : Autograd기능 동작시 미분값을 w(변수).grad에 저장

In [75]:
w = torch.tensor(1.0, requires_grad=True)

In [76]:
a = w * 3

In [77]:
l = a ** 2

In [78]:
l

tensor(9., grad_fn=<PowBackward0>)

In [79]:
l.backward()

In [80]:
w.grad

tensor(18.)